# Generated by Django 2.1.5 on 2020-12-19 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0003_auto_20201218_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='profilePicture',
            field=models.ImageField(default='default.jpg', upload_to='profile_pics'),
        ),
    ]
